### PR TITLE
fix(highlight): remove previous highlights before applying new ones

### PR DESCRIPTION
**Pull request by brokenbyte**
This PR adds the changes from https://github.com/mrjones2014/nvim-ts-rainbow/pull/11

Without the changes in this PR, deleting+reinserting a bracket confuses the color matching resulting in
matching pairs having different colors.

recording of the behavior with the latest version of this plugin:

[original_ts_rainbow.webm](https://user-images.githubusercontent.com/37650823/232252514-22167893-1622-40fe-9f33-189cb5ba372b.webm)

recording of the behavior with my changes:

[fixed_ts_rainbow.webm](https://user-images.githubusercontent.com/37650823/232252337-936d176c-c29b-47bd-8ade-b5a58f4feafc.webm)

One issue I found with these changes that are also present in  https://github.com/mrjones2014/nvim-ts-rainbow/pull/11 (but not the current state of this repo) is if pairs are followed by a comment (~~in rust specifically, doesn't appear to affect other languages~~ it is affecting all languages actually) the pairs will have no highlighting until you update the line:

[fixed_ts_with_trailing_comment.webm](https://user-images.githubusercontent.com/37650823/232252591-fb5e9fea-fc45-4542-82ac-8f8571997ef1.webm)

I'd be happy to look in to fixing that as well, and plan on doing so, but if you have any ideas as to what might be
causing that and where to look it would be appreciated.

### CODE REVIEW

**Comment by HiPhish** [comment]
That's pretty cool, I will have to daily-drive your changes for a few days to see if the issue is gone. I do have a question though: would it not make more sense to use `nvim_buf_clear_namespace` instead of the loop to clear everything from that namespace? I see it as just an implementation detail that the highlighting is stored in extmarks.

```lua
vim.api.nvim_buf_clear_namespace(bufnr, lib.nsid, change[1], change[3] + 1)
```

> One issue I found with these changes that are also present in mrjones2014/nvim-ts-rainbow#11 (but not the current state of this repo) is if pairs are followed by a comment (~~in rust specifically, doesn't appear to affect other languages it is affecting all languages actually~~) the pairs will have no highlighting until you update the line

Do you have the `comment` parser installed? I can replicate the issue when it is installed, but not when it is uninstalled.

**Comment by HiPhish** [comment]
> so if you don't see an issue with clearing the whole namespace I can do that.

It's fine, namespaces are used for highlighting only here.

> Do you think we can do something to make it work in both cases? I'm not super familiar with tree-sitter or why that specific parser would be causing these issues.

It would be good if we could make it work with the `comment` parser. My blind guess would be that somehow Neovim assigns the text to the wrong language (i.e. `comment` instead of `rust`) after the tree has changed.

**Comment by HiPhish** [comment]
I have figured out why the highlighting gets erased. It's actually pretty
obvious in hindsight. The function `update_range` gets called once per
language, in our case first for Rust then for comments. Note how you clear the
namespace:

```lua
vim.api.nvim_buf_clear_namespace(bufnr, lib.nsid, change[1], change[3] + 1)
```

The namespace is cleared for the entire line. When we open a buffer the entire
buffer is initially highlighted for all languages. The order of events is as
follows:

1. Highlight the Rust code
  1. Clear namespace on all lines with Rust code
  2. Highlight all Rust code
2. Highlight the comment code
  1. Clear namespace on all lines with comments
  2. Highlight all comments

Here step `2.1` ends up wiping all the highlighting from the first step on that
particular line. The same would happen with any other injected language (e.g.
Vim script in Lua), it just so happens that comments are the most likely to be
on the same line as other code.

How can we avoid this problem? There is no way of clearing a namespace for a
column range. I think the best option is to have separate namespaces for each
language. Whenever a new language is encountered a new namespace will be
created and cached for later use. We can safely reuse the same namespace across
buffers and users will very likely only have a few languages per session, so
the number of namespaces should plateau out very quickly.

**Comment by HiPhish** [comment]
I have just pushed a new commit which should resolve the issue fully. Please test it on your end. I will daily drive it for a few days and if there are no issues reported by either of use I can merge the changes into `master`.

**Comment by brokenbyte** [comment]
Just pulled your changes and they're working on the examples I've been using to play with on my end. Your explanation definitely makes a lot of sense as well, and I agree that this is very unlikely to create an extreme number of namespaces. One situation I could see creating more than a couple per session is a complex markdown/latex document with codeblocks embedding several different languages, but even then something like 10 different languages seems like a pretty high upper bound for even a complex session, and that doesn't seem like it would take a ton of resources unless namespaces are way more involved than I would guess.

Even with that I would guess the worst effect of this would be potentially slightly slower load times on initially opening these complex files, but subsequent updates should be fine since we're only clearing it for a specific line/subset of lines on updates. Do you think that would be enough to make the experience sluggish?

**Comment by HiPhish** [comment]
> Do you think that would be enough to make the experience sluggish?

There is only one way to know: try it out. I don't have a large file at hand, but I could use a Lorem Ipsum generator or something to create a stress test text file. It would be good in general to have stress test files.

**Comment by brokenbyte** [comment]
I don't know if this is in scope for this PR, but it seems that this makes embedded languages in markdown files to highlight wonky (and even inconsistently):

[embedded_languages_rainbow.webm](https://user-images.githubusercontent.com/37650823/233222356-c2773ffd-8436-4690-81c1-1091cc6f3ef2.webm)

The current master branch of this plugin has some issues as well, but they're at least consistent, so here's a screenshot:

image

**Comment by HiPhish** [comment]
Can you try Markdown now please?

The issue was that as new injected languages are added to the buffer we add new parsers to the language tree. However, these new parsers never had the necessary callbacks registered, because callbacks only get registered once. I have now added a callback for the `on_child_added` event which will set up the new parser correctly. At least I hope it is correct now.

**Comment by brokenbyte** [comment]
Hm it's still inconsistently highlighting different parts of the embedded languages:

[markdown_stress_test.webm](https://user-images.githubusercontent.com/37650823/233514630-96284f86-e775-4830-bef6-160ccf019a49.webm)

The current master branch does this as well.

I also noticed that in both the current master and this branch the HTML highlighting is coloring the angle brackets but not the actual tag themselves:
image

**Comment by brokenbyte** [comment]
Hm ok so after working on an issue with a different plugin I made a setup to test stuff with an isolated minimal nvim config in a docker container, so I decided to throw this in there and test it, and it seems like it's working correctly now, and also figured out the setting to make it highlight html tags instead of just the brackets.

The minimal config:

```lua
local ensure_packer = function()
    local fn = vim.fn
    local install_path = fn.stdpath("data") .. "/site/pack/packer/opt/packer.nvim"
    if fn.empty(fn.glob(install_path)) > 0 then
        fn.system({ "git", "clone", "--depth", "1", "https://github.com/wbthomason/packer.nvim", install_path })
        vim.cmd([[packadd packer.nvim]])
        return true
    end
    return false
end

local packer_bootstrap = ensure_packer()

vim.cmd("packadd packer.nvim")
local packer = require("packer")

packer.startup({
    function(use)
        use({
            "wbthomason/packer.nvim",
            opt = true,
        })

        use("nvim-lua/plenary.nvim")

        use({
            "yashguptaz/calvera-dark.nvim",
            config = function() require("calvera").set() end,
        })

        use({
            "brokenbyte/nvim-ts-rainbow2",
            -- "mrjones2014/nvim-ts-rainbow",
            -- "HiPhish/nvim-ts-rainbow2",
            -- "~/code/nvim/nvim-ts-rainbow2",
            dependencies = "nvim-treesitter",
        })

        use({
            "nvim-treesitter/nvim-treesitter",
            config = function()
                require("nvim-treesitter.configs").setup({
                    ensure_installed = {
                        "lua",
                        "markdown",
                        "c",
                        "python",
                        "bash",
                        "json",
                        "html",
                        "css",
                        "vim",
                        "javascript",
                    },

                    highlight = {
                        enable = true,
                    },

                    rainbow = {
                        enable = true,
                        query = {
                            "rainbow-parens",
                            html = "rainbow-tags",
                        },
                        strategy = require("ts-rainbow").strategy.global,
                    },
                })
            end,
        })

        if packer_bootstrap then require("packer").sync() end
    end,
})

vim.o.termguicolors = true

vim.o.encoding = "UTF-8"

vim.o.background = "dark"

vim.o.shiftwidth = 4

vim.o.number = true

vim.o.signcolumn = "yes"
```

and I have a docker container that I'm running it in:
```dockerfile
from archlinux:latest

RUN mkdir -p /home/user/.config/nvim

RUN useradd -M user -p "$(openssl passwd -1 password)"

RUN chown -R user:user /home/user

RUN sed -i "/NoProgressBar/d" /etc/pacman.conf

RUN pacman -Sy neovim git python3 gcc sudo --noconfirm

RUN echo "user ALL=(ALL:ALL) NOPASSWD: ALL" >> /etc/sudoers

WORKDIR /home/user

USER user

# Clear packer_compiled.lua every time the container launches
RUN echo "rm -f ~/.config/nvim/plugin/packer_compiled.lua" >> /home/user/.bash_profile

# Start a login shell so it loads ~/.bash_profile
CMD ["bash", "--login"]
```

It's also working on my laptop with my normal configs as well, so there must have been something weird going on with my configs between last time I tried it and now or something updated that fixed it.

Either way, things seem to be working correctly on my end. Will keep using it and let you know if anything comes up.

**Comment by brokenbyte** [comment]
And of course as soon as I post that I find something, but since it's something that's related to another plugin I'm not sure it's really the problem of these changes.

When I move a line down with [nvim-gomove](https://github.com/booperlv/nvim-gomove) the highlighting on the brackets says:

[gomove_rainbow.webm](https://user-images.githubusercontent.com/37650823/233820414-3fe76e44-29cb-422e-8500-89a6b9b76974.webm)

Note that when I delete the line and paste it again with `ddp` the highlighting _does_ go away.

After looking in to what `nvim-gomove` does to actually move the line, it seems like it's just
`:start_line,end_line move dest`

So for the line in the recording, that's just `:7,7 move 8`, which reproduces the behavior when run manually.

Also, if the line is not highlighted (e.g. after a `ddp`), moving it _in_ to the code block correctly adds highlights to the line when moved with `nvim-gomove`, so it's correctly updating the highlights on additions to the code block with `:m`, but not removals.

**Comment by HiPhish** [comment]
I have been able to replicate the issue using just `:move`. The problem is that the line has highlighting in the `lua` namespace, but only tree changes in the `markdown` languages are reported. This means that no Lua highlighting is removed. But then why does `ddp` work? Extmarks move along with the text, so if we execute `:move` we move the text along with its extmarks, but if we run `dd` we remove the text and its extmarks, then we run `p` to past a new line of the same contents but without the extmarks of the original.

This seems like a bug in Neovim to me. Clearly when I move a line of code out of the Lua block this should be a change in the Lua tree as well. Moving the line back up does fire events for both languages, so that's why the highlighting inside the code blocks works.

**Comment by HiPhish** [comment]
I am merging this now since the main issues are solved and the current state is no worse than the previous `master`. As for moving code out of a code block in Markdown, that part is up to Neovim now.

**Comment by HiPhish** [comment]
Just a heads-up, I have fixed the issue with the highlighting persisting when the Lua code is moved out of the Markdown block. This is a fundamental problem because Tree-sitter does not distinguish between types of events, it only reports that some sort of event happened in a given region. With this in mind, there is nothing that can be done on the Neovim side.

My solution is to delete all extmarks other than those of the current language on every change. This is additional overhead, but I believe the impact will be minimal. Most users will have only a handful of languages in use per session, and there won't be many changes at a given time.

**Pull request merged**
