### PR TITLE
Add Vue and Scss support

### PR DESCRIPTION
**Pull request by tuanha168**

### CODE REVIEW

**Comment by tuanha168** [comment]
#13

**Comment by HiPhish** [comment]
Can you please provide a sample Vue file as well? It needs to cover the various way of writing Vue, such as embedding different languages (e.g. embedding Javascript and embedding Typescript). If Vue does not allow to have two script blocks then you can create separate test files.

See the files under `test/highlight` for examples of what I mean.

**Comment by tuanha168** [comment]
@HiPhish 
Thanks, I added 2 sample file with diffirent language on each block.

**Comment by HiPhish** [comment]
Thank you, it is now merged. I made a couple of changes:

- More test files
- Added `script_element` and `style_element` to query

I prefer more but shorter test files over fewer but larger ones. We don't have any limit on the number of files.

One note though: you might see weird highlighting because of neovim/neovim#17060. The problem is that in a query like

```
(element
  ((start_tag
      ["<" ">"] @opening)
   (element
      (self_closing_tag
        ["<" "/>"] @intermediate))?
   (end_tag
      ["</" ">"] @closing))) @container
```

the capture `["<" ">"] @opening` captures two nodes, but Neovim's current Tree-sitter implementation cannot handle this, it only returns the first match.

**Pull request merged**
