### PR TITLE
feat(nix): add queries for nix

### PR DESCRIPTION
**Pull request by mrcjkb**
I will dogfeed this and add more as I come across them...

### CODE REVIEW

**Comment by HiPhish** [comment]
Is this PR ready for merge or do you want to add more patterns?

**Comment by mrcjkb** [comment]
FYI, I just realised I had forgotten to add a query for `interpolation`.
Just added it now :)

**Comment by HiPhish** [comment]
Please rebase on `master` once more.

**Comment by HiPhish** [comment]
Merged, thank you.

**Pull request merged**
